version: '3.8'

services:
  angularstarter-release:
    image: eztekdockerhub.azurecr.io/angularstarter-release
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: production
        MAX_OLD_SPACE_SIZE: 8192
    command: [ nginx-debug, '-g', 'daemon off;' ]
